#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these at the top of the stages section. The wizard writes only
# to the project and repository bound here, never to ones it would infer from
# where it was started.
TOTAL_STAGES=0
PROJECT_ROOT="" # the project's absolute, canonical path (`pwd -P` in its root)
ENV_FILE=""     # absolute path of its env file; defaults to $PROJECT_ROOT/.env
GITHUB_REPO=""  # OWNER/NAME that set_secret and set_var write to

_STAGE_INDEX=0
_BOUND=0
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# _die "msg" stops the wizard before it writes anything else.
_die() { printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET" >&2; exit 1; }

# _bind checks, once, that the wizard is about to touch the project it was
# generated for: PROJECT_ROOT is an existing absolute, canonical directory,
# the wizard runs from inside it, ENV_FILE lives under it, and GITHUB_REPO,
# when set, is [HOST/]OWNER/NAME. Anything else stops the wizard before any
# write.
_bind() {
  (( _BOUND )) && return 0
  local here dir repo='^([A-Za-z0-9.-]+/)?[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$'
  [[ "$PROJECT_ROOT" == /* && -d "$PROJECT_ROOT" && "$(cd -P -- "$PROJECT_ROOT" && pwd -P)" == "$PROJECT_ROOT" ]] \
    || _die "PROJECT_ROOT must be the project's absolute, canonical path (got '$PROJECT_ROOT')"
  here=$(pwd -P) || here=""
  [[ "$here" == "$PROJECT_ROOT" || "$here" == "$PROJECT_ROOT"/* ]] \
    || _die "this wizard sets up $PROJECT_ROOT: cd there and run it again"
  ENV_FILE="${ENV_FILE:-$PROJECT_ROOT/.env}"
  dir=$(cd -P -- "$(dirname -- "$ENV_FILE")" 2>/dev/null && pwd -P) || dir=""
  [[ "$ENV_FILE" == /* && ( "$dir" == "$PROJECT_ROOT" || "$dir" == "$PROJECT_ROOT"/* ) ]] \
    || _die "ENV_FILE must be an absolute path in an existing directory under $PROJECT_ROOT (got '$ENV_FILE')"
  [[ -z "$GITHUB_REPO" || "$GITHUB_REPO" =~ $repo ]] \
    || _die "GITHUB_REPO must be [HOST/]OWNER/NAME (got '$GITHUB_REPO')"
  _BOUND=1
}

# banner "Title" shows the opening frame: what this wizard does, and where.
banner() {
  _bind
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · %s%s%s\n\n' "$DIM" "$TOTAL_STAGES" "$PROJECT_ROOT" "${GITHUB_REPO:+ · GitHub $GITHUB_REPO}" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# .env lines are written for dotenv-style loaders (dotenv, dotenv-expand,
# python-dotenv, `set -a; . ./.env`): a plain value bare, anything else in
# single quotes. Those loaders read ' \ $ and control characters differently
# even inside quotes, so a value holding one is refused, not stored.
_ENV_PLAIN='^[A-Za-z0-9_./:@%+=,-]*$'
_env_quotable() { [[ "$1" != *[\'\\\$[:cntrl:]]* ]]; }

# _env_line KEY VALUE prints KEY's .env line, or fails when VALUE has no form
# that every one of those loaders reads back unchanged.
_env_line() {
  if [[ "$2" =~ $_ENV_PLAIN ]]; then printf '%s=%s' "$1" "$2"
  elif _env_quotable "$2"; then printf "%s='%s'" "$1" "$2"
  else return 1; fi
}

# _existing KEY: current value of KEY in ENV_FILE, if any, read back from the
# form write_env stores. A line in any other form counts as no value, so it is
# never reused as something it isn't.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line value inner
  line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  value="${line#*=}"; inner="${value#\'}"; inner="${inner%\'}"
  if [[ "$value" =~ $_ENV_PLAIN ]]; then printf '%s' "$value"
  elif [[ "$value" == "'$inner'" ]] && _env_quotable "$inner"; then printf '%s' "$inner"
  else return 1; fi
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  _bind
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  _bind
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# _upsert_env KEY LINE writes ENV_FILE's other lines plus LINE to a temp file
# beside it, then renames that over ENV_FILE. Fails, leaving ENV_FILE as it
# was, if any step does, including a read of the existing file.
_upsert_env() {
  local key="$1" line="$2" tmp status=0
  tmp=$(mktemp "$ENV_FILE.XXXXXX") || return 1
  if [[ -e "$ENV_FILE" ]]; then
    grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || status=$?
    (( status <= 1 )) || { rm -f "$tmp"; return 1; } # 1 is "no other lines"
  fi
  if ! { printf '%s\n' "$line" >> "$tmp" && mv -f "$tmp" "$ENV_FILE"; }; then
    rm -f "$tmp"; return 1
  fi
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent. A lock directory beside ENV_FILE keeps two
# runs from dropping each other's keys; the wizard stops, writing nothing, if
# the value can't be stored as is, the lock stays held, or the file can't be
# read or replaced.
write_env() {
  local key="$1" value="$2" line lock tries=0
  _bind
  line=$(_env_line "$key" "$value") \
    || _die "the value for $key has a ' \\ \$ or control character, which .env loaders read differently; nothing was written, so store it by hand"
  lock="$ENV_FILE.lock"
  until mkdir -- "$lock" 2>/dev/null; do
    [[ -d "$lock" ]] || _die "couldn't write beside $ENV_FILE; it is unchanged"
    (( ++tries < 30 )) || _die "$ENV_FILE is in use by another run; it is unchanged (if none is running, remove $lock)"
    sleep 0.1
  done
  if ! _upsert_env "$key" "$line"; then
    rmdir -- "$lock" 2>/dev/null || true
    _die "couldn't update $ENV_FILE; it is unchanged"
  fi
  rmdir -- "$lock" 2>/dev/null || true
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions secret on GITHUB_REPO via gh.
# Falls back to a warning (and records it) if gh is unavailable or
# unauthenticated.
set_secret() {
  local name="$1" value="$2"
  _bind
  [[ -n "$GITHUB_REPO" ]] || _die "set_secret $name: no GITHUB_REPO is bound"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" --repo "$GITHUB_REPO" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s on %s\n' "$GREEN" "$RESET" "$name" "$GITHUB_REPO"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name --repo $GITHUB_REPO)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions variable (non-secret) on
# GITHUB_REPO.
set_var() {
  local name="$1" value="$2"
  _bind
  [[ -n "$GITHUB_REPO" ]] || _die "set_var $name: no GITHUB_REPO is bound"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --repo "$GITHUB_REPO" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s on %s\n' "$GREEN" "$RESET" "$name" "$GITHUB_REPO"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name on $GITHUB_REPO")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=1
PROJECT_ROOT="/path/to/project" # `pwd -P` in the project root
ENV_FILE="$PROJECT_ROOT/.env"
GITHUB_REPO="OWNER/NAME"        # confirmed with the user; "" if nothing goes to GitHub

banner "Stripe setup"

# ── Example stage: replace with your real steps ───────────────────────────
stage "Stripe: API keys"
say "We'll grab your Stripe test keys and store them for local dev + CI."
open_url "https://dashboard.stripe.com/test/apikeys"
step "On the API keys page, copy the Publishable key (starts pk_test_)."
ask STRIPE_PUBLISHABLE_KEY "Paste the publishable key:"
step "Click 'Reveal test key' on the Secret key row, then copy it."
ask_secret STRIPE_SECRET_KEY "Paste the secret key:"
write_env STRIPE_PUBLISHABLE_KEY "$STRIPE_PUBLISHABLE_KEY"
write_env STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"
set_secret STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"   # CI needs this one
# ──────────────────────────────────────────────────────────────────────────

finish
